/**
 * BIND zone file parser & serialiser.
 *
 * Parses a subset of BIND-format zone files into DnsRecordCreate objects and
 * serialises DnsRecordResponse arrays back to BIND text.
 *
 * Supported record types: A, AAAA, CNAME, TXT, MX, NS, PTR, SRV, CAA
 * TTL directives ($TTL) are honoured. $ORIGIN is ignored (records already
 * include the FQDN).
 */

import { DnsRecordCreate, DnsRecordResponse, DnsRecordType } from "@/types/api";

const SUPPORTED: Set<string> = new Set([
  "A", "AAAA", "CNAME", "TXT", "MX", "NS", "PTR", "SRV", "CAA",
]);

interface ParseResult {
  records: DnsRecordCreate[];
  errors: string[];
}

export function parseBind(text: string): ParseResult {
  const records: DnsRecordCreate[] = [];
  const errors: string[] = [];
  let defaultTtl = 300;

  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i].replace(/;.*$/, "").trim(); // strip comments
    if (!raw) continue;

    // $TTL directive
    const ttlDirective = raw.match(/^\$TTL\s+(\d+)/i);
    if (ttlDirective) {
      defaultTtl = parseInt(ttlDirective[1], 10);
      continue;
    }

    // Skip other directives
    if (raw.startsWith("$")) continue;

    // Record line: name [ttl] [class] type rdata
    // Regex: name  optional_ttl  optional_class  type  rdata
    const m = raw.match(
      /^(\S+)\s+(?:(\d+)\s+)?(?:IN\s+)?([A-Z]+)\s+(.+)$/i
    );
    if (!m) {
      errors.push(`Line ${i + 1}: Could not parse: ${raw}`);
      continue;
    }

    const [, rawName, rawTtl, rawType, rdata] = m;
    const type = rawType.toUpperCase() as DnsRecordType;

    if (!SUPPORTED.has(type)) {
      errors.push(`Line ${i + 1}: Unsupported type ${type} — skipped`);
      continue;
    }

    const name = rawName.endsWith(".") ? rawName : `${rawName}.`;
    const ttl = rawTtl ? parseInt(rawTtl, 10) : defaultTtl;

    records.push({
      name,
      type,
      ttl,
      value: rdata.trim(),
      routing_policy: "Simple",
    });
  }

  return { records, errors };
}

export function serialiseBind(
  zoneName: string,
  records: DnsRecordResponse[],
  defaultTtl = 300
): string {
  const lines: string[] = [
    `; Zone file for ${zoneName}`,
    `; Generated by AWS Route53 Clone — ${new Date().toISOString()}`,
    `$TTL ${defaultTtl}`,
    "",
  ];

  for (const r of records) {
    // Format: name  ttl  IN  type  value
    lines.push(`${r.name}\t${r.ttl}\tIN\t${r.type}\t${r.value}`);
  }

  return lines.join("\n");
}

export function downloadText(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
